export const JOB_TITLE_REPOSITORY = Symbol('JOB_TITLE_REPOSITORY')
export const JOB_TITLE_VERSION_REPOSITORY = Symbol('JOB_TITLE_VERSION_REPOSITORY')
export const JOB_TITLE_LEVEL_REPOSITORY = Symbol('JOB_TITLE_LEVEL_REPOSITORY') 