export enum Segment {
    LABORATORY = 'LABORATORY',
    HOSPITAL = 'HOSPITAL',
    MEDICAL_METALLURGY = 'MEDICAL_METALLURGY',
    ANIMAL_HEALTH = 'ANIMAL_HEALTH',
    VEHICLE_INSPECTION = 'VEHICLE_INSPECTION',
    VEHICLE_REGISTRATION = 'VEHICLE_REGISTRATION',
    DRIVING_SCHOOL = 'DRIVING_SCHOOL'
}
