apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-deployment
  namespace: core-homolog # ou core-homolog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      containers:
        - name: core-service
          image: lucassuntech/core-service:develop # ou :develop
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: core-db-secret
                  key: DATABASE_URL
