name: Show Secrets (Temporary)

on:
  workflow_dispatch:

jobs:
  show-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Criar arquivo com os secrets
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" > secrets.txt
          echo "DOCKER_ACCESS_TOKEN=${{ secrets.DOCKER_ACCESS_TOKEN }}" >> secrets.txt
          echo "VPS_HOST=${{ secrets.VPS_HOST }}" >> secrets.txt
          echo "VPS_USER=${{ secrets.VPS_USER }}" >> secrets.txt
          echo "VPS_SSH_KEY=${{ secrets.VPS_SSH_KEY }}" >> secrets.txt
          echo "DATABASE_URL_PROD=${{ secrets.DATABASE_URL_PROD }}" >> secrets.txt

      - name: Upload dos secrets como artifact
        uses: actions/upload-artifact@v4
        with:
          name: secrets
          path: secrets.txt
