name: Show Secrets (Temporary)

on:
  workflow_dispatch: # 🔥 Só roda manualmente para segurançaa

jobs:
  show-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar valores dos secrets (temporário)
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
          echo "DOCKER_ACCESS_TOKEN=${{ secrets.DOCKER_ACCESS_TOKEN }}"
          echo "VPS_HOST=${{ secrets.VPS_HOST }}"
          echo "VPS_USER=${{ secrets.VPS_USER }}"
          echo "VPS_SSH_KEY=${{ secrets.VPS_SSH_KEY }}"
          echo "DATABASE_URL_PROD=${{ secrets.DATABASE_URL_PROD }}"
